Repository gogearbox/gearbox, pull requests merged in 2020-06, with the labels that each got.

#30 Fixes #25 Added custom methods
  gearbox.go
  gearbox_test.go
Labels: enhancement

#31 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, maintenance

#32 Support parameters
  .gitignore
  README.md
  context.go
  context_test.go
  gearbox.go
  gearbox_test.go
  go.sum
  router.go
  router_test.go
  tst.go
Labels: enhancement

#35 support caching and settings
  cache.go
  cache_test.go
  context_test.go
  gearbox.go
  gearbox_test.go
  router.go
  router_test.go
  tst.go
  tst_test.go
Labels: chore, enhancement

#36 #21 support grouping routes
  README.md
  context_test.go
  gearbox.go
  gearbox_test.go
  router.go
  router_test.go
Labels: chore, enhancement

#37 Support optional parameter
  README.md
  router.go
  router_test.go
Labels: enhancement

#38 add fast http settings
  cache.go
  cache_test.go
  gearbox.go
  gearbox_test.go
  router.go
  router_test.go
Labels: chore, enhancement

#39 Add tests
  cache_test.go
  router.go
  router_test.go
Labels: enhancement

#40 fix route match
  gearbox.go
  router.go
  router_test.go
Labels: bug

#42 use maps instead of tst
  .github/auto_assign.yml
  .github/dependabot.yml
  .github/workflows/security.yml
  .github/workflows/test_and_build.yml
  README.md
  cache.go
  cache_test.go
  context.go
  gearbox.go
  gearbox_test.go
  go.mod
  router.go
  router_test.go
  tst.go
  tst_test.go
  utils.go
  utils_test.go
Labels: enhancement

#46 Add Nagy to reviewers.
  .github/auto_assign.yml
Labels: enhancement

#50 remove unused string
  router.go
Labels: enhancement

#52 Support prefork
  gearbox.go
  gearbox_test.go
  go.mod
  go.sum
  router.go
Labels: enhancement

#53 Added support for SSL #51
  gearbox.go
  gearbox_test.go
  ssl-cert-snakeoil.crt
  ssl-cert-snakeoil.key
Labels: chore, enhancement

#54 Add default max request url length
  gearbox.go
  router.go
Labels: chore, enhancement
