Repository gogearbox/gearbox, pull requests merged in 2020-07, with the labels that each got.

#58 Add Sponsor Trella
  .github/FUNDING.yml
  README.md
  assets/trella-sponsor.png
Labels: chore

#59 Update README.md
  .gitignore
  README.md
Labels: chore, documentation

#60 Add erply
  README.md
  assets/erply-user.png
Labels: chore, documentation, enhancement

#64 Improve routing
  .github/workflows/test_and_build.yml
  README.md
  cache.go
  cache_test.go
  context.go
  context_test.go
  gearbox.go
  gearbox_test.go
  go.sum
  router.go
  router_test.go
  tree.go
  tree_test.go
Labels: enhancement

#65 update README
  README.md
  assets/ssl-cert-snakeoil.crt
  assets/ssl-cert-snakeoil.key
  context.go
  gearbox.go
  gearbox_test.go
  router.go
  tree.go
Labels: chore

#66 Add benchmark results
  README.md
  assets/benchmark-pipeline.png
Labels: chore
